version: "3.8"
services:
  app:
    build:
      context: .
      args:
        APP_ENV: production
      options:
        no-cache: true
    environment:
      NODE_ENV: production
    ports:
      - 5050:5050