version: "3.8"
services:
  app:
    restart: unless-stopped
    build:
      context: .
      args:
        APP_ENV: production
    environment:
      NODE_ENV: production
    ports:
      - 5050:5050