version: "3"
services:
  app:
    build:
      context: .
      args:
        APP_ENV: production
    environment:
      NODE_ENV: production
    volumes:
      - ./files:/usr/app/files
    ports:
      - 3000:3000